"""
Core data models for the Trading Simulation Laboratory.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from enum import Enum
from datetime import datetime


class AssetType(Enum):
    STOCK = "stock"
    CRYPTO = "crypto"
    ETF = "etf"


class SignalType(Enum):
    BUY = "buy"
    SELL = "sell"


@dataclass
class Signal:
    """A trade signal generated by a strategy."""
    ticker: str
    signal_type: SignalType
    asset_type: AssetType
    confidence: float  # 0.0 to 1.0
    reason: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    generated_at: datetime = None

    def __post_init__(self):
        if self.generated_at is None:
            self.generated_at = datetime.utcnow()


@dataclass
class ProfileConfig:
    """Configuration for a single strategy profile."""
    profile_id: str
    display_name: str
    description: str
    asset_type: AssetType
    data_source: str  # "openinsider", "coingecko", "fmp_congress", "none"
    initial_capital: float = 10000.0
    position_size_pct: float = 10.0
    max_positions: int = 10
    stop_loss_pct: float = -10.0
    take_profit_pct: float = 20.0
    max_holding_days: int = 60
    commission: float = 6.95
    schedule: str = "weekdays"  # "weekdays" or "daily"
    extra_params: Dict[str, Any] = field(default_factory=dict)
